### ISSUE TITLE
Multiple levels

### ISSUE THREAD

**Issue by pahakalle** [frenski/quizy-memorygame#13]
Would be nice to have an easy way to make multiple different levels.

**Comment by frenski** [comment]
@pahakalle Thanks for the suggestion! Could you please give an example of what do you mean by "multiple different levels". Thanks!

**Comment by brubrant** [comment]
I have created that here: [https://gamesfortraders.com/memory-game/](https://gamesfortraders.com/memory-game/)  (the site sill in beta)

3 different levels: 12, 18 and 24 "cards". Just initialize the game with the proper number after the user select the level.

**Comment by frenski** [comment]
@pahakalle Is a solution like the one @brubrant proposes something that what you are looking for? If yes, I will close the issue.
Thanks!

**Comment by pahakalle** [comment]
Yeah, kinda. Tough i ended up using json and a bit of javascript to change the li tags when you complete a "level" 😂
